### ISSUE TITLE
[Question] Overall package roadmap and future

### ISSUE THREAD

**Issue by incendial** [pattobrien/sidecar#102]
Hi, I just came across this package and after reading the readme now curious - how is what you're building different from the Dart Code Metrics from the features standpoint? For me looks like the package has the same motivation and features set (at least listed in readme). If so, maybe we can instead join our effort and make DCM better? 🙂

**Comment by pattobrien** [comment]
Hey Dmitry! The purpose of Sidecar is to be more like a platform for rules to be created upon, rather than a set of defined lint rules that you have in DCM (I suppose this could be made a bit clearer in the readme). As you probably know, this is a goal that's shared by ```analyzer_plugin``` and even package ```dart_custom_lints```; this package serves as a different architecture of the same goals. 

For example, one of the objectives I set out to achieve was for separate rule packages to run within a single isolate, so that a single file doesn't need to be analyzed multiple times from multiple isolates. From preliminary testing with packages built on top of sidecar (e.g. [design_system_lints](https://pub.dev/packages/design_system_lints)), everything seems to work very reliably and with great performance, shy of a few bugs left to iron out.

That said, my intention is 100% to work together with you and the analyzer team on all of our projects. And ultimately I hope that if sidecar becomes a relatively successful project with a strong architecture, that perhaps it'll become a blueprint for the official analyzer_plugin. Time will tell, but regardless I'm looking forward to working together in whatever capacity makes most sense. 😊

**Comment by incendial** [comment]
> The purpose of Sidecar is to be more like a platform for rules to be created upon, rather than a set of defined lint rules that you have in DCM

The thing with DCM is that it's not just about the rules, but more about the whole DX (linting, metrics, commands to maintain the codebase (unused files, code, etc.) and more things to come). So I treat it more like a developers toolkit.

> As you probably know, this is a goal that's shared by analyzer_plugin and even package dart_custom_lints; this package serves as a different take at achieving the same goals.

Right now I'm focusing on the new version of DCM without using the plugins API (coz all the measurements I have even with a single plugin are still worse than having no plugin at all), but considering this feature (ability to create custom lints) is highly requested even from us, I think that it will be added to the DCM relatively soon.

And I can see how it can be a part of what we already provide and how, if we decide to join efforts, both our goals (create a performant platform for creating custom rules and make DCM feature rich and more adopted by the community) can be achieved. But if it's not what you're looking for, it's totally cool, I'll be happy to collaborate on the plugins future.

I even think that removing the dependency on the plugins unblocks a way to run custom rules without an isolate, but this hypothesis is yet to be validated.

> For example, one of the objectives I set out to achieve was for separate rule packages to run within a single isolate, so that a single file doesn't need to be analyzed multiple times from multiple isolates. From preliminary testing with packages built on top of sidecar (e.g. [design_system_lints](https://pub.dev/packages/design_system_lints)), everything seems to work very reliably and with great performance, shy of a few bugs left to iron out.

This is actually a good way to rethink the plugins in general and this is one of the options the Dart team itself considers for plugins implementation (as far as I can tell). Great job!

**Comment by pattobrien** [comment]
so here's my two cents: I'm actually very excited that you're thinking about the same goals too. I've used DCM myself and know that its capable of much more than just lints (sorry if it sounded like I was suggesting otherwise!). I'm not sure exactly what your roadmap looks like for DCM, but  over the past 4 months I've created Sidecar from scratch on the basis of meeting the goals I outlined, and currently things **_already_** work very well, with a lot of other features planned for Q1 2023. I've been putting in ~60 hours a week into this project, trying out many different implementations to see what API feels best, as this is a liberty that a new project can have since it's not constrained by a large organization (Dart / analyzer) or existing users (DCM). 

Ultimately, I absolutely want to collaborate - I cannot stress that enough! - but I don't think all of this code needs to be funneled through DCM to do that. After all, sidecar works today, so why not test it out as is? :)

Also, I agree that the ```analyzer_plugin``` package has a lot of baggage (and was started sooo long ago). In fact, sidecar already has its own server that works independently of the plugin (the analyzer_plugin's ```ServerPlugin``` simply interacts with the server). So even though ```analyzer_plugin``` could be replaced if necessary, my preferred objective would be to influence the design decisions of that package by proving a really great user experience and performance via ```sidecar```. If we show a good PoC, I'm hopeful the Dart team will agree to inherit some of these functionalities directly into the official packages, and hopefully make sidecar obsolete! 

This is why, for example, sidecar ```Rules``` very closely look like the ```LintRules``` of the official analyzer/linter package, so that one day we can unite. This is also why I've documented so many architecture decisions for you or anyone else to read through (docs folder), to either give feedback on or simply to learn from / copy.

I'm going to set up a discord channel over the next week so that we could have a place to continue collaborating, does that sound good to you?

**Comment by incendial** [comment]
> a liberty that a new project can have since it's not constrained by a large organization (Dart / analyzer) or existing users (DCM).

If you design a new feature (even module) you're not that limited, at least if we talk about the DCM. But I agree. 

>  my preferred objective would be to influence the design decisions of that package by proving a really great user experience and performance via sidecar. If we show a good PoC, I'm hopeful the Dart team will agree to inherit some of these functionalities directly into the official packages, and hopefully make sidecar obsolete!
> This is why, for example, sidecar Rules very closely look like the LintRules of the official analyzer/linter package, so that one day we can unite. This is also why I've documented so many architecture decisions for you or anyone else to read through (docs folder), to either give feedback on or simply to learn from / copy.

I see, I guess that's where we differ in our vision - I'd like DCM to exist independently. But I like the overall goal - it worth trying out!

> Ultimately, I absolutely want to collaborate - I cannot stress that enough! - but I don't think all of this code needs to be funneled through DCM to do that. After all, sidecar works today, so why not test it out as is? :)

The only problem with that is that DCM has a different approach with the rules implementation in general.  I think that it will be optimised to a singular visitor for all the rules in the future, but the model of a rule is still different (has configuration, for example). So, unfortunately, Sidecar can't be reused directly. 

> Ultimately, I absolutely want to collaborate - I cannot stress that enough!
> I'm going to set up a discord channel over the next week so that we could have a place to continue collaborating, does that sound good to you?

Yes! Having a community around the static analysis thing is definitely a community I'd love to be part of. When we started the DCM, the only reference we had was the Dart Angular plugin (and maybe one for Built value) and it was hard to figure out some things 🙂.

>  I'm not sure exactly what your roadmap looks like for DCM

Unfortunately, I can't share it yet, but more details will come soon when the beta will become available.

I guess I'll close this issue since the initial question is answered, but looking forward to the further collaboration! You can contact me [on twitter](https://twitter.com/_incendial) if anything.
